### ISSUE TITLE
createRedPacket 方法的 hashedPackets 参数，最好直接由后端生成

### ISSUE THREAD

**Issue by sjpsega** [keeper402/Hongbao#1]
https://github.com/keeper402/Hongbao/blob/cb31a22e2b1950bb5293c72caf2cd0b160dbc33f/contracts/LuckyRedPacket.sol#L25

**Comment by keeper402** [comment]
服务端是可以的做。提供一个入参 keyword和n，出参size为n的hash数组。
顺便，服务端还要一个当前cnt的接口，在领取红包时提供给前端查询。

**Comment by xu8117** [comment]
![image](https://github.com/keeper402/Hongbao/assets/39123862/9f961b73-8bf3-41a8-9282-871d7a5ea8c5)
监控合约调用记录，是否会得到所有的keyHash和hashedPackets，导致RedPacket被清空

**Comment by keeper402** [comment]
> ![image](https://private-user-images.githubusercontent.com/39123862/339470343-9f961b73-8bf3-41a8-9282-871d7a5ea8c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyOTcwODcsIm5iZiI6MTcxODI5Njc4NywicGF0aCI6Ii8zOTEyMzg2Mi8zMzk0NzAzNDMtOWY5NjFiNzMtOGJmMy00MWE4LTkyODItODcxZDdhNWVhOGM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDE2Mzk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNzg5MmI1ZmI0ZjIzMTIzNGY0NWIzMjliZmI5MTJhYzU4MGY1MTNkMDVhMmUyZjM0MjA0NzhmMjI3YmFkMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YIGEAED9E_i0PgWxq1UYRGPaGdA3h49NOIBI70QjE4s) 监控合约调用记录，是否会得到所有的keyHash和hashedPackets，导致RedPacket被清空

RedPacket被清空是指被程序领完吗。不会，领红包和发红包的参数是不一样的。等我优化下文档吧，之前可能没写清楚。
