### ISSUE TITLE
createRedPacket 方法中，遇到关键词相同，直接执行 delete。若原来的红包如果未被领完，最好给予退回或其他更好得处理

### ISSUE THREAD

**Issue by sjpsega** [keeper402/Hongbao#2]
https://github.com/keeper402/Hongbao/blob/cb31a22e2b1950bb5293c72caf2cd0b160dbc33f/contracts/LuckyRedPacket.sol#L31

```solidity
//之前使用过的关键词，先把原纪录删了
if (redPackets[keyHash].cnt > 0) {
    delete redPackets[keyHash];
}
```

**Comment by keeper402** [comment]
不会出现这种情况，这行代码是在红包被领完后执行。
不过可以添加一个过有效期自动退回的方案。有个问题在于有效期该怎么触发，可以讨论一下（没有交易就没法执行代码
