### ISSUE TITLE
领红包逻辑漏洞

### ISSUE THREAD

**Issue by xu8117** [keeper402/Hongbao#4]
![image](https://github.com/keeper402/Hongbao/assets/39123862/d72a6659-44cd-4f3e-b7ce-812e6c61e5e1)
在区块链上，所有合约代码，redPackets，RedPacket的hashedPackets都是可以看到的。分析合约代码后，从redPackets中拿出一个bytes32，拿到对应的RedPacket的hashedPackets，取hashedPackets中的第一个（等价于领取红包中的doubleHashedKey），已知代码bytes32 doubleHashedKey = keccak256(abi.encodePacked(hashedKey));  已知doubleHashedKey ，已知abi.encodePacked()源码，已知keccak256源码，可反推出hashedKey。
![image](https://github.com/keeper402/Hongbao/assets/39123862/1ffd9b22-97f2-463c-8474-e8e6e51c563a)

**Comment by keeper402** [comment]
类似md5，hash函数是都是单向的，不会泄露。
